install: ""
php_version: ""
filesystem_version: ""
prod_install: bcmountainstg
stage_install: ""
dev_install: ""
push_environment: ""
pull_environment: ""
last_ssh_event: "2022-10-25T21:00:57-06:00"
last_push_event: "2022-10-25T21:00:49-06:00"
mysql_volume_mount_type: ""
mysql_root_password: ""
mysql_user_password: ""
mysql_user_name: ""
mysql_database_name: ""
xdebug_off_by_default: false
force_ssl: false
wp_debug: false
wp_debug_cli: false
